### ISSUE TITLE
Limit color scale heat map

### ISSUE THREAD

**Issue by ccruizm** [icbi-lab/infercnvpy#63]
### Description of feature

Good day,

Thanks for implementing this in python. The speed is mindblowing. I would like to limit the color scale of the heatmap to enhance the areas with iCNV. However when using `vmax` and `vmin` I get and error (`ValueError: Passing both norm and vmin/vmax/vcenter is not allowed.`) do you have a way to do it, please?

Thanks again

**Comment by grst** [comment]
So the issue is that I pass a custom `norm` to the `matrixplot` function: 
https://github.com/icbi-lab/infercnvpy/blob/bab74f1115c8b26c27f14ee6e70cc1900c544644/src/infercnvpy/pl/_chromosome_heatmap.py#L70

It would be easy to add a check to the function that only uses the `TwoSlopeNorm` if no `vmax` or `vmin` is set (happy to accept a PR), or allow to pass a custom `norm` to the function.

**Comment by DamarisDeng** [comment]
Hi, thanks for you work! Did you add the check? I really need it now.

**Comment by grst** [comment]
I currently don't have time to look into this, feel free to submit a PR!
